### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by lambda-m** [bmsuisse/daxparser#1]
As I found no other contact details, I hope you don't mind me abusing a github issue to say thank you!

I was looking all over for a DAX parser, and although yours has a "very limited" API, it provides everything I needed for a specific project. This saved me a ton of work, and allows for some fine grained insights into a bunch of PowerBI reports we have. I use it together with pbi-tools and TMDLSerializer for custom analysis.

**Comment by aersam** [comment]
Nice to hear! Always good if it helps. We used it for a very specific use case, but there it saved a lot of time

**Comment by aersam** [comment]
I'll close this now, I also release your changes in 0.1.3
